In [1]:
# Question1a
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])




Reversed: [5 4 6 3 2 1]


In [2]:
# Question1b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.ravel())
print(array1.flatten())

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [3]:
#Question1c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1, arr2)


True

In [4]:
# Question1d
x = np.array([1,2,3,4,5,1,2,1,1,1])
from collections import Counter
most_common = Counter(x).most_common(1)[0][0]
print("Most frequent:", most_common)
print("Indices:", np.where(x == most_common))

Most frequent: 1
Indices: (array([0, 5, 7, 8, 9]),)


In [10]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
from collections import Counter
most_common = Counter(y).most_common(1)[0][0]
print("Most frequent:", most_common)
print("Indices:", np.where(y == most_common))

Most frequent: 1
Indices: (array([0, 1, 2]),)


In [5]:
# q1 e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Row-wise sum
row_sum = np.sum(gfg, axis=1)

# iii. Column-wise sum
col_sum = np.sum(gfg, axis=0)

print(total_sum)
print(row_sum)
print(col_sum)


45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [11]:
#q1 f
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Diagonal sum:", np.trace(n_array))
print("Eigen values:", np.linalg.eigvals(n_array))
eigvals, eigvecs = np.linalg.eig(n_array)
print("Eigen vectors:\n", eigvecs)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))

Diagonal sum: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [ ]:
# q1 g
# i.
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)

# ii.
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())

print(product1)
print(cov1)
print(product2)
print(cov2)

In [ ]:
#q1 h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner = np.inner(x, y)

# Outer product (flattened)
outer = np.outer(x, y)

# Cartesian product
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(inner)
print(outer)
print(cartesian)


[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
# Q2 a
array = np.array([[1, -2, 3],[-4, 5, -6]])

# i. Absolute
abs_array = np.abs(array)

# ii. Percentiles
flat = array.flatten()
percentiles = np.percentile(flat, [25, 50, 75])
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print(abs_array)
print(percentiles)
print(col_percentiles)
print(row_percentiles)

# iii. Stats
mean = np.mean(flat)
median = np.median(flat)
std = np.std(flat)

col_mean = np.mean(array, axis=0)
row_mean = np.mean(array, axis=1)

print(mean, median, std)
print(col_mean)
print(row_mean)


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5]
[ 0.66666667 -1.66666667]


In [13]:
#q2 b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print(floor_vals)
print(ceil_vals)
print(trunc_vals)
print(round_vals)


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
# Q3 a
a = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(a))
print("Sorted Indices:", np.argsort(a))
print("4 Smallest:", np.sort(a)[:4])
print("5 Largest:", np.sort(a)[-5:])

Sorted: [ 10  16  16  52  54  62 453]
Sorted Indices: [0 3 4 1 5 2 6]
4 Smallest: [10 16 16 52]
5 Largest: [ 16  52  54  62 453]


In [16]:
#Q3 b
b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integers:", b[b == b.astype(int)])
print("Floats:", b[b != b.astype(int)])

Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]


In [ ]:
import numpy as np
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    
    if len(arr.shape) == 2:  # Grayscale
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print("Saved as grayscale_image.txt")
    elif len(arr.shape) == 3 and arr.shape[2] == 3:  # RGB
        arr_reshaped = arr.reshape(-1, 3)
        np.savetxt("rgb_image.txt", arr_reshaped, fmt='%d')
        print("Saved as rgb_image.txt")
    else:
        print("Unsupported image format")


img_to_array("your_image_path_here.jpg")



Unsupported image format


In [ ]:
#q4 b
# For grayscale
grayscale = np.loadtxt("grayscale_image.txt", dtype=int)
print(grayscale)

# For RGB
rgb = np.loadtxt("rgb_image.txt", dtype=int).reshape(-1, 3)
print(rgb)



FileNotFoundError: grayscale_image.txt not found.